"""Write results, baseline, and the markdown summary. Summary is generated from JSON."""
from __future__ import annotations

import json
from pathlib import Path

from tests.harness.case_schema import SEVERITY_ORDER, Case
from tests.harness.loader import load_cases
from tests.harness.metrics import compute_metrics

HERE = Path(__file__).parent
RESULTS = HERE / "harness_results.json"
BASELINE = HERE / "baseline.json"
RETRIEVAL = HERE / "retrieval_results.json"
SUMMARY = HERE / "RESULTS.md"


def load_results_doc(path: Path = RESULTS) -> dict:
    """Accept both formats: legacy list of per-case dicts, or {meta, results}."""
    if not path.exists():
        return {"meta": {"mode": "none"}, "results": []}
    data = json.loads(path.read_text())
    if isinstance(data, list):
        return {"meta": {"mode": "legacy-live-7-case", "note": "pre-expansion run, 7 cases"}, "results": data}
    return data


def write_results(path: Path, meta: dict, results: list[dict], metrics: dict) -> None:
    path.write_text(json.dumps({"meta": meta, "metrics": metrics, "results": results}, indent=2) + "\n", encoding="utf-8")


def load_baseline(path: Path = BASELINE) -> dict | None:
    return json.loads(path.read_text()) if path.exists() else None


def baseline_snapshot(results: list[dict], metrics: dict, git_sha: str) -> dict:
    return {"git_sha": git_sha, "metrics": metrics,
            "per_case": {r["id"]: bool(r["passed"]) for r in results if r.get("status") == "ok"}}


def diff_text(old: dict | None, new: dict) -> str:
    if not old:
        return "No previous baseline."
    om, nm = old["metrics"], new["metrics"]
    rows = [
        ("standard pass rate", om["pass_rate_standard"]["rate"], nm["pass_rate_standard"]["rate"]),
        ("adversarial pass rate", om["pass_rate_adversarial"]["rate"], nm["pass_rate_adversarial"]["rate"]),
        ("escalation recall", om["escalation"]["recall"], nm["escalation"]["recall"]),
        ("calibration ECE", om["calibration"]["ece"], nm["calibration"]["ece"]),
    ]
    lines = [f"{n:24s} {a} -> {b}" for n, a, b in rows]
    for cat, v in nm["per_category"].items():
        lines.append(f"  {cat:22s} {om['per_category'].get(cat, {}).get('rate')} -> {v['rate']}")
    flips = [i for i, p in old["per_case"].items() if p and not new["per_case"].get(i, False)]
    lines.append(f"cases that passed before and fail now: {flips or 'none'}")
    return "\n".join(lines)


def _pct(x) -> str:
    return "n/a" if x is None else f"{x * 100:.1f}%"


def suite_stats(cases: list[Case]) -> dict:
    techs = sorted({t.split(".")[0] for c in cases for t in c.expect.techniques_any})
    sev = {s: sum(1 for c in cases if s in c.expect.severity_in) for s in SEVERITY_ORDER}
    sole = {s: sum(1 for c in cases if c.expect.severity_in == [s]) for s in SEVERITY_ORDER}
    groups: dict[str, int] = {}
    for c in cases:
        groups[c.group] = groups.get(c.group, 0) + 1
    return {"total": len(cases), "groups": groups, "techniques": techs, "severity_accepted": sev,
            "severity_sole": sole, "reviewed": sum(c.human_reviewed for c in cases),
            "should_refuse": sum(1 for c in cases if not c.relevant_chunks),
            "injection": groups.get("adversarial:injection", 0)}


def render_summary(cases: list[Case], results_doc: dict, retrieval_doc: dict | None) -> str:
    st = suite_stats(cases)
    out = ["# Harness results", "", "Generated by `python -m tests.harness.report`. Do not edit by hand.", ""]
    out += ["## Suite", "",
            f"- Cases: {st['total']} ({', '.join(f'{k} {v}' for k, v in sorted(st['groups'].items()))})",
            f"- Distinct MITRE techniques expected: {len(st['techniques'])} ({', '.join(st['techniques'])})",
            f"- Out-of-corpus cases (no relevant chunk, must refuse): {st['should_refuse']}",
            f"- Prompt-injection cases: {st['injection']}",
            "- Severity levels accepted by at least one case: " + ", ".join(f"{k} {v}" for k, v in st["severity_accepted"].items()),
            f"- Human-reviewed cases: {st['reviewed']} of {st['total']} (the rest are Claude-drafted and pending review)", ""]

    out += ["## Retrieval (measured, local embeddings, no LLM)", ""]
    if retrieval_doc:
        m, meta = retrieval_doc["metrics"], retrieval_doc["meta"]
        out += [f"Embedding model {meta['model']}, {meta['corpus_chunks']} chunks, {m['answerable_queries']} answerable queries, "
                f"{m['refusal_queries']} should-refuse queries, git {meta['git_sha']}.", "",
                "| Metric | Value |", "|---|---|",
                f"| recall@{m['k']} | {m['recall_at_k']} |",
                f"| recall@{m['k']} after 0.20 threshold | {m['recall_at_k_after_threshold']} |",
                f"| hit@{m['k']} | {m['hit_at_k']} |",
                f"| MRR | {m['mrr']} |",
                f"| refusal precision at {m['threshold']} | {m['refusal_precision']} |",
                f"| refusal recall at {m['threshold']} | {m['refusal_recall']} |", "",
                "Threshold sweep (refusal = top-1 score below threshold):", "",
                "| Threshold | Refusal precision | Refusal recall | recall@4 after threshold | TP | FP | FN |", "|---|---|---|---|---|---|---|"]
        for s in retrieval_doc["sweep"]:
            out.append(f"| {s['threshold']:.2f} | {s['refusal_precision']} | {s['refusal_recall']} | "
                       f"{s['recall_at_k_after_threshold']} | {s['refusal_tp']} | {s['refusal_fp']} | {s['refusal_fn']} |")
        out.append("")
    else:
        out += ["Not yet measured. The CI job `retrieval-eval` produces `retrieval_results.json`.", ""]

    out += ["## Triage (LLM in the loop)", ""]
    meta = results_doc.get("meta", {})
    mode = meta.get("mode")
    if mode == "live":
        mt = results_doc["metrics"]
        out += [f"Live run {meta.get('recorded_at')}, git {meta.get('git_sha')}, model {meta.get('model')}, "
                f"{mt['evaluated']} of {mt['total_cases']} cases evaluated.", "",
                "| Metric | Value |", "|---|---|",
                f"| Standard pass rate | {_pct(mt['pass_rate_standard']['rate'])} ({mt['pass_rate_standard']['passed']}/{mt['pass_rate_standard']['n']}) |",
                f"| Adversarial pass rate | {_pct(mt['pass_rate_adversarial']['rate'])} ({mt['pass_rate_adversarial']['passed']}/{mt['pass_rate_adversarial']['n']}) |",
                f"| Severity accuracy (in range) | {_pct(mt['severity']['accuracy'])} |",
                f"| MITRE top-1 | {_pct(mt['mitre']['top1'])} |",
                f"| MITRE any-match | {_pct(mt['mitre']['any_match'])} |",
                f"| Escalation precision / recall | {_pct(mt['escalation']['precision'])} / {_pct(mt['escalation']['recall'])} |",
                f"| Refusal precision / recall | {_pct(mt['refusal']['precision'])} / {_pct(mt['refusal']['recall'])} |",
                f"| Injection resistance | {_pct(mt['injection']['resistance'])} ({mt['injection']['cases']} cases) |",
                f"| Schema-failure rate | {_pct(mt['schema_failure_rate'])} |",
                f"| Latency p50 / p95 | {mt['latency_seconds']['p50']} s / {mt['latency_seconds']['p95']} s |",
                f"| Cost per triage (estimate from token usage) | ${mt['cost_per_triage_usd']} |", ""]
    else:
        out += ["**The 100-case suite has not been run live.** No cassettes are committed, so no LLM metric is claimed.",
                "Record them with `python -m tests.harness.test_harness --record --update-baseline` (about 100 calls, estimated 1 to 2 USD), then rerun `python -m tests.harness.report`.", ""]
        legacy = results_doc["results"] if mode == "legacy-live-7-case" else []
        if legacy:
            ok = sum(1 for r in legacy if r.get("passed"))
            lat = [r["latency_seconds"] for r in legacy if r.get("latency_seconds") is not None]
            out += ["Last real live run (pre-expansion, 7 cases, July 2026):", "",
                    f"- Passed {ok}/{len(legacy)}",
                    f"- Mean latency {sum(lat) / len(lat):.1f} s per alert" if lat else "", ""]
    return "\n".join(l for l in out if l is not None) + "\n"


def main() -> None:
    cases = load_cases()
    rdoc = json.loads(RETRIEVAL.read_text()) if RETRIEVAL.exists() else None
    SUMMARY.write_text(render_summary(cases, load_results_doc(), rdoc), encoding="utf-8")
    print(f"wrote {SUMMARY}")


if __name__ == "__main__":
    main()
